# EDA

In [1]:
import pandas as pd
from taxipred.utils.constants import TAXI_CSV_PATH

df = pd.read_csv(TAXI_CSV_PATH)
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [2]:
df.shape

(1000, 11)

In [3]:
df.columns

Index(['Trip_Distance_km', 'Time_of_Day', 'Day_of_Week', 'Passenger_Count',
       'Traffic_Conditions', 'Weather', 'Base_Fare', 'Per_Km_Rate',
       'Per_Minute_Rate', 'Trip_Duration_Minutes', 'Trip_Price'],
      dtype='object')

In [4]:
df.info()

# We can observe that 5% of the data is NaN.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       950 non-null    float64
 1   Time_of_Day            950 non-null    object
 2   Day_of_Week            950 non-null    object
 3   Passenger_Count        950 non-null    float64
 4   Traffic_Conditions     950 non-null    object
 5   Weather                950 non-null    object
 6   Base_Fare              950 non-null    float64
 7   Per_Km_Rate            950 non-null    float64
 8   Per_Minute_Rate        950 non-null    float64
 9   Trip_Duration_Minutes  950 non-null    float64
 10  Trip_Price             951 non-null    float64
dtypes: float64(7), object(4)
memory usage: 86.1+ KB

- We can observe that if we were to drop the rows with null values, we would lose almost 45% of our data which would impact our learned model

In [5]:
nan_rows = df[df.isna().any(axis=1)]

display(nan_rows.sample(10))
print(f"Total rows with NaN: {len(nan_rows)}")

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
462,37.56,Morning,Weekday,4.0,Low,NaN,3.22,1.93,0.15,56.81,84.2323
698,8.56,Night,Weekend,4.0,Medium,Clear,2.63,NaN,0.33,83.03,46.2939
963,20.08,Afternoon,Weekend,1.0,Low,Clear,2.80,1.05,0.42,NaN,49.5082
62,41.61,Evening,Weekend,3.0,Low,Rain,2.79,0.78,0.15,NaN,47.3148
707,40.68,Morning,Weekday,3.0,NaN,Clear,3.01,1.11,0.12,84.00,58.2448
676,6.49,Morning,Weekday,3.0,Medium,NaN,3.68,NaN,0.19,31.66,NaN
544,31.29,Night,Weekday,NaN,Medium,Clear,4.10,1.90,0.28,57.45,79.6370
692,25.87,Afternoon,Weekday,2.0,NaN,Rain,4.35,1.26,0.23,112.39,62.7959
937,45.80,Evening,Weekday,2.0,Medium,Rain,NaN,0.84,0.11,31.43,NaN
278,35.40,Morning,Weekday,3.0,NaN,Clear,4.47,1.98,0.46,93.88,117.7468

Total rows with NaN: 438

In [6]:
df["Day_of_Week"].value_counts()

Day_of_Week
Weekday    655
Weekend    295
Name: count, dtype: int64

In [9]:
df["Time_of_Day"].value_counts()

Time_of_Day
Afternoon    371
Morning      283
Evening      203
Night         93
Name: count, dtype: int64

In [10]:
df["Traffic_Conditions"].value_counts()

Traffic_Conditions
Low       397
Medium    371
High      182
Name: count, dtype: int64

In [11]:
df["Weather"].value_counts()

Weather
Clear    667
Rain     227
Snow      56
Name: count, dtype: int64

In [7]:
df.describe()

,Trip_Distance_km,Passenger_Count,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
count,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,951.000000
mean,27.070547,2.476842,3.502989,1.233316,0.292916,62.118116,56.874773
std,19.905300,1.102249,0.870162,0.429816,0.115592,32.154406,40.469791
min,1.230000,1.000000,2.010000,0.500000,0.100000,5.010000,6.126900
25%,12.632500,1.250000,2.730000,0.860000,0.190000,35.882500,33.742650
50%,25.830000,2.000000,3.520000,1.220000,0.290000,61.860000,50.074500
75%,38.405000,3.000000,4.260000,1.610000,0.390000,89.055000,69.099350
max,146.067047,4.000000,5.000000,2.000000,0.500000,119.840000,332.043689

- Target variable: Trip_Price
- Features related to pricing calculation (Base_Fare, Per_Km_Rate, Per_Minute_Rate) will not be used as model inputs.
- Missing values are present (~5%) and will be handled during preprocessing.


- Columns such as Base_Fare, Per_Km_Rate, and Per_Minute_Rate are directly used in price calculation.
To avoid data leakage, these columns will not be used as input features during modeling.