# EDA

In [2]:
import pandas as pd
from taxipred.utils.constants import TAXI_CSV_PATH

df = pd.read_csv(TAXI_CSV_PATH)
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180

In [2]:
df.shape

(1000, 11)

In [3]:
df.columns

Index(['Trip_Distance_km', 'Time_of_Day', 'Day_of_Week', 'Passenger_Count',
       'Traffic_Conditions', 'Weather', 'Base_Fare', 'Per_Km_Rate',
       'Per_Minute_Rate', 'Trip_Duration_Minutes', 'Trip_Price'],
      dtype='object')

In [4]:
df.info()

# We can observe that 5% of the data is NaN.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Trip_Distance_km       950 non-null    float64
 1   Time_of_Day            950 non-null    object
 2   Day_of_Week            950 non-null    object
 3   Passenger_Count        950 non-null    float64
 4   Traffic_Conditions     950 non-null    object
 5   Weather                950 non-null    object
 6   Base_Fare              950 non-null    float64
 7   Per_Km_Rate            950 non-null    float64
 8   Per_Minute_Rate        950 non-null    float64
 9   Trip_Duration_Minutes  950 non-null    float64
 10  Trip_Price             951 non-null    float64
dtypes: float64(7), object(4)
memory usage: 86.1+ KB

In [5]:
df.isna().mean().sort_values()

Trip_Price               0.049
Trip_Distance_km         0.050
Day_of_Week              0.050
Time_of_Day              0.050
Traffic_Conditions       0.050
Weather                  0.050
Base_Fare                0.050
Passenger_Count          0.050
Per_Km_Rate              0.050
Per_Minute_Rate          0.050
Trip_Duration_Minutes    0.050
dtype: float64

In [6]:
nan_rows = df[df.isna().any(axis=1)]

display(nan_rows.sample(10))
print(f"Total rows with NaN: {len(nan_rows)}")

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
872,NaN,Afternoon,NaN,4.0,Low,Clear,4.81,0.65,0.26,10.76,28.7716
703,7.59,Afternoon,Weekday,2.0,High,NaN,3.95,0.67,0.25,59.78,23.9803
607,18.85,NaN,Weekday,3.0,Low,Clear,2.25,0.87,0.30,98.29,48.1365
19,15.27,Morning,NaN,NaN,Low,Clear,3.93,0.73,0.12,NaN,27.3543
50,48.51,Evening,Weekday,3.0,High,Rain,NaN,1.00,0.48,110.18,104.1764
711,30.19,Morning,Weekday,2.0,Medium,NaN,2.37,0.76,0.40,113.33,70.6464
598,10.42,Morning,Weekday,1.0,Low,Clear,NaN,0.85,0.28,112.71,43.0058
84,NaN,Night,Weekday,1.0,Medium,Clear,3.38,1.50,0.31,58.31,45.8161
149,14.65,Evening,Weekend,2.0,High,Clear,3.74,1.79,NaN,29.58,40.0207
9,35.70,Afternoon,Weekday,2.0,Low,Rain,3.39,1.52,0.47,NaN,75.5657

Total rows with NaN: 438

In [3]:
df.describe()

,Trip_Distance_km,Passenger_Count,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
count,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,951.000000
mean,27.070547,2.476842,3.502989,1.233316,0.292916,62.118116,56.874773
std,19.905300,1.102249,0.870162,0.429816,0.115592,32.154406,40.469791
min,1.230000,1.000000,2.010000,0.500000,0.100000,5.010000,6.126900
25%,12.632500,1.250000,2.730000,0.860000,0.190000,35.882500,33.742650
50%,25.830000,2.000000,3.520000,1.220000,0.290000,61.860000,50.074500
75%,38.405000,3.000000,4.260000,1.610000,0.390000,89.055000,69.099350
max,146.067047,4.000000,5.000000,2.000000,0.500000,119.840000,332.043689

- Target variable: Trip_Price
- Features related to pricing calculation (Base_Fare, Per_Km_Rate, Per_Minute_Rate) will not be used as model inputs.
- Missing values are present (~5%) and will be handled during preprocessing.


- Columns such as Base_Fare, Per_Km_Rate, and Per_Minute_Rate are directly used in price calculation.
To avoid data leakage, these columns will not be used as input features during modeling.